# Generated by Django 2.1 on 2020-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrenheit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculatordetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='calculatordetails',
            name='userName',
        ),
    ]
