# Generated by Django 2.1 on 2020-01-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrenheit_calculator', '0002_auto_20200118_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='calculatordetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fahrenheit_calculator.UserDetails'),
            preserve_default=False,
        ),
    ]
